package net.kmaster.cookiemom.dao;

import de.greenrobot.dao.DaoException;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table BOOTH.
 */
@SuppressWarnings("ALL")
public class Booth {

    private Long id;
    private String boothLocation;
    private String boothAddress;
    private java.util.Date boothDate;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient BoothDao myDao;

    private List<BoothAssignments> scoutsAssigned;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Booth() {
    }

    public Booth(Long id) {
        this.id = id;
    }

    public Booth(Long id, String boothLocation, String boothAddress, java.util.Date boothDate) {
        this.id = id;
        this.boothLocation = boothLocation;
        this.boothAddress = boothAddress;
        this.boothDate = boothDate;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBoothDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBoothLocation() {
        return boothLocation;
    }

    public void setBoothLocation(String boothLocation) {
        this.boothLocation = boothLocation;
    }

    public String getBoothAddress() {
        return boothAddress;
    }

    public void setBoothAddress(String boothAddress) {
        this.boothAddress = boothAddress;
    }

    public java.util.Date getBoothDate() {
        return boothDate;
    }

    public void setBoothDate(java.util.Date boothDate) {
        this.boothDate = boothDate;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<BoothAssignments> getScoutsAssigned() {
        if (scoutsAssigned == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BoothAssignmentsDao targetDao = daoSession.getBoothAssignmentsDao();
            List<BoothAssignments> scoutsAssignedNew = targetDao._queryBooth_ScoutsAssigned(id);
            synchronized (this) {
                if (scoutsAssigned == null) {
                    scoutsAssigned = scoutsAssignedNew;
                }
            }
        }
        return scoutsAssigned;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetScoutsAssigned() {
        scoutsAssigned = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return this.getBoothLocation();
    }
    // KEEP METHODS END

}
